//
//  AISummaryCard.swift
//  SmartTravelJournal
//
//  Created by Valentyn Verovkin on 09.08.2026.
//

import SwiftUI
import SwiftData
import FoundationModels

struct AISummaryCard: View {

    let viewModel: TripSummaryViewModel
    let trip: Trip

    @Environment(\.modelContext) private var modelContext

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {

            // Header
            HStack {
                Image(systemName: "sparkles")
                    .foregroundStyle(.white)

                Text("AI TRIP SUMMARY")
                    .font(.caption)
                    .fontWeight(.semibold)
                    .foregroundStyle(.white)

                Spacer()
            }
            .padding()
            .background(
                LinearGradient(
                    colors: [.blue, .indigo],
                    startPoint: .leading,
                    endPoint: .trailing
                )
            )

            // Content
            VStack(alignment: .leading, spacing: 12) {

                if viewModel.isGenerating {
                    ProgressView("Generating summary...")

                } else if let errorMessage = viewModel.errorMessage {
                    Text(errorMessage)
                        .foregroundStyle(.red)

                    Button("Retry") {
                        Task {
                            await viewModel.retry(
                                for: trip,
                                context: modelContext
                            )
                        }
                    }

                } else if let summary = viewModel.summary {
                    Text(summary.summary)

                    if !summary.highlights.isEmpty {
                        VStack(alignment: .leading, spacing: 6) {
                            ForEach(summary.highlights, id: \.self) { highlight in
                                Label(
                                    highlight,
                                    systemImage: "sparkles"
                                )
                                .font(.caption)
                            }
                        }
                    }

                } else {
                    Text(
                        "AI features require Apple Intelligence."
                    )
                    .foregroundStyle(.secondary)
                }

                if viewModel.summary != nil {
                    Text(
                        "Generated by Foundation Models · On-device"
                    )
                    .font(.caption2)
                    .foregroundStyle(.secondary)
                }
            }
            .padding()
        }
        .clipShape(
            RoundedRectangle(cornerRadius: 12)
        )
        .overlay {
            RoundedRectangle(cornerRadius: 12)
                .stroke(
                    Color.blue.opacity(0.2),
                    lineWidth: 1
                )
        }
    }
}
